### ISSUE TITLE
Reproduce results

### ISSUE THREAD

**Issue by vincehass** [uber-research/vargp#1]
Hi,

I am trying to reproduce your paper experiments, however the "results" folder (var-gp_2020_results.zip) is broken. Is it possible to upoad a working version of this folder?.
Thank you!

**Comment by thangbui** [comment]
Hi @activatedgeek, do you have still have a copy of this?

**Comment by activatedgeek** [comment]
Hey @vincehass, somehow I missed this notification. Thanks for bringing this up. I now realize that my old deployment may have been broken. Can you try downloading again from [here](https://u.perhapsbay.es/var-gp-results)?

**Comment by vincehass** [comment]
@activatedgeek and @thangbui Thank you!
